services:

  db:
    image: postgres:16
    container_name: banking-postgres

    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: banking-app

    depends_on:
      - db

    ports:
      - "8080:8080"

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

volumes:
  postgres_data: