services:

  db:
    image: postgres:16
    container_name: banking-postgres

    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: banking-redis

    ports:
      - "6379:6379"

  app:
    build: .
    container_name: banking-app

    depends_on:
      - db
      - redis
      - kafka

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://db:5432/bankdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      REDIS_HOST: banking-redis
      REDIS_PORT: 6379

      KAFKA_SERVER: kafka:9092

  prometheus:
    image: prom/prometheus
    container_name: banking-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: banking-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: banking-zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: banking-kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data: