services:

  db:
    image: postgres:16
    container_name: banking-postgres

    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: banking-redis

    ports:
      - "6379:6379"

  app:
    build: .
    container_name: banking-app

    depends_on:
      - db
      - redis

    ports:
      - "8080:8080"

    environment:
      DB_URL: jdbc:postgresql://db:5432/bankdb
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}

      REDIS_HOST: banking-redis
      REDIS_PORT: 6379

  prometheus:
    image: prom/prometheus
    container_name: banking-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: banking-grafana

    ports:
      - "3000:3000"

    depends_on:
      - prometheus

volumes:
  postgres_data: